# Generated by Django 2.1.3 on 2018-12-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=30)),
                ('descripcionProducto', models.CharField(max_length=30)),
                ('precioProducto', models.IntegerField(max_length=10)),
            ],
        ),
    ]
