# Generated by Django 2.1.3 on 2018-12-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipoProducto',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
