# Generated by Django 2.1.3 on 2018-12-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_producto_tipoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.IntegerField(),
        ),
    ]
