# Generated by Django 2.1.3 on 2018-12-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181206_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ImagenProducto',
            field=models.ImageField(default=0, upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
