# Generated by Django 2.1.3 on 2018-12-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181206_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='ImagenProducto',
            new_name='image',
        ),
    ]
