# Generated by Django 2.1.3 on 2018-12-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_tienda_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='apellidoEmpleado',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombreEmpleado',
        ),
    ]
