# Generated by Django 2.1.3 on 2018-12-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181210_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellidoEmpleado',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombreEmpleado',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
